### ISSUE TITLE
Homepage grid of all images that have been added.

### ISSUE THREAD

**Issue by zamiang** [builtbylane/donda-mood-board#27]

**Comment by zamiang** [comment]
<img width="1061" alt="screenshot 2016-11-20 14 15 09" src="https://cloud.githubusercontent.com/assets/110563/20465515/a7ca8ecc-af2c-11e6-8a43-3634e7a6af84.png">

**Comment by zamiang** [comment]
![pasted_image_at_2016_11_20_02_18_pm_480](https://cloud.githubusercontent.com/assets/110563/20465516/b1bf3f40-af2c-11e6-8684-ecb124e5f0e6.png)

**Comment by zamiang** [comment]
Clicking an image brings you to the collection page for the image

**Comment by builtbylane** [comment]
you'll need this helper, autoprefixer doesn't put it in. 
https://github.com/builtbylane/donda-mood-board/blob/master/src/styles/_helpers.scss#L36

**Comment by zamiang** [comment]
ok sure.

**Comment by zamiang** [comment]
I believe those css properties are to add momentum scrolling for iOS. I didn't think we were supporting iOS with this?
