### ISSUE TITLE
Paginate Recent Items

### ISSUE THREAD

**Issue by builtbylane** [builtbylane/donda-mood-board#33]

**Comment by roomnoise** [comment]
@builtbylane I know we just talked about skip/limit, but it's not great ultimately in mongo.  In fact, I just realized we had to drop it in favor of date pagination for this very reason

https://scalegrid.io/blog/fast-paging-with-mongodb/

If the goal here is ultimate scroll anyway, we should go off created_at + limit.

**Comment by builtbylane** [comment]
Cool. Go for it. Thanks!
