### ISSUE TITLE
Search for multiple tags + project name

### ISSUE THREAD

**Issue by builtbylane** [builtbylane/donda-mood-board#34]

**Comment by roomnoise** [comment]
@builtbylane by 'project name' do you mean we're returning both items and projects in the call?

**Comment by builtbylane** [comment]
@roomnoise no, we're always returning items, but if a Project called "shoes". Searching "shoes" should return all items in that project as well any items tagged as shoes

**Comment by roomnoise** [comment]
ok, thx
